#!/bin/sh
 
ssh app@5.135.240.8 <<EOF
  cd /nant-it
  git pull
  fuser -k 80/tcp
  fuser -k 3000/tcp
  cd /nant-it/web
  nohup npm start &
  cd /nant-it/db
  nohup npm start &
 # npm install --production
 # forever restartall
  exit
EOF
